title: FarmLife-Wiki
description: "Wiki f√ºr FarmLife: Badoras!"
theme: just-the-docs
favicon_ico: "/assets/images/favicon.ico"

url: https://wiki.badoras.life

aux_links:
  Website: "https://badoras.life"
  Impressum: "https://badoras.life/impressum"
  Source Code: "https://github.com/FLBadoras/wiki"

aux_links_new_tab: true

color_scheme: dark


collections:
  team_members:
    name: Team Members
  commands:
    permalink: "/:collection/:path/"
    name: Commands
    output: true
  systems:
    permalink: "/:collection/:path/"
    output: true
  jobs:
    permalink: "/:collection/:path/"
    output: true
  lists:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    systems:
      name: Systeme
      nav_fold: true
    jobs:
      name: Jobs
      nav_fold: true
    lists:
      name: Listen
      nav_fold: true

callouts:
  note:
    title: Note
    color: blue
  contributing:
    title: Contributing
    color: yellow
